name: CI

# Only trigger, when the linting workflow succeeded
on:
  workflow_run:
    workflows: ["Linting"]
    types:
      - completed

jobs:
  # make sure our tests are passing
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...

  # make sure go build works on various OS/Go versions
  go-build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    # only run this job if the "test" job has passed
    needs: [test]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.1'

    - name: Build
      run: go build -v ./...
