name: Test Scrapers

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  # make sure our scrapers are still working
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]

    runs-on: ubuntu-latest

    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Tidy
      run: go mod tidy

    - name: Test
      run: go test -v ./...
